#!/usr/bin/env bash
#Lets help you Read the f**king manual
manual_page=$1
echo $(man $manual_page) | pv -qcL 40
if [[ $? -gt 0 ]]; then
    help $manual_page
fi
$manual_page
firefox https://google.com/search?q=how+to+use+$manual_page
